# Generated by Django 5.1.1 on 2024-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_rename_stoptimes_stoptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Unknown Trip', max_length=100),
        ),
    ]
