# Generated by Django 5.1.1 on 2024-12-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.stop'),
        ),
    ]
